# Configuration of the port (so that it does not clash with anything)
server.port=8083

# Connection to the PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/cinematch_db
spring.datasource.username=postgres
spring.datasource.password=S3rg1024!

# Hibernate: Creates the tables automatically if they don't exist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
